services:
  - type: web
    name: fueltrack
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        value: changez-moi
    disk:
      name: fueltrack-data
      mountPath: /data
      sizeGB: 1
